### ISSUE TITLE
[求助] 请问盒子自带的 FlexGet 如何正确启用插件？

### ISSUE THREAD

**Issue by lacafjh** [amefs/quickbox-lite#173]
我从另一篇 [博客](https://shyi.io/2022/04/14/flexget/) 了解到 QuickBox Lite 中 FlexGet 的插件目录是在 `/home/${username}/.local/flexget3/plugins`，检查后发现本地无此文件夹，手动建立同名目录。以安装隔壁的 NexusPHP 增强插件 [Juszoe/flexget-nexusphp](https://github.com/Juszoe/flexget-nexusphp) 为例，采用如下步骤（其中 qboxl 是在 TUI 安装过程中为 QuickBox Lite 建立的用户）：

```shell
# 建立插件目录
$ mkdir /home/qboxl/.local/flexget3/plugins
# 将插件下载到插件目录
$ cd /home/qboxl/.local/flexget3/plugins && wget https://github.com/Juszoe/flexget-nexusphp/releases/download/v1.4/nexusphp.py
$ reboot
```

重启完成后，尝试到 WebUI 修改 config 如下：

```
tasks:
  website-name:
    rss:
      url: https://sample.com/xxxxxx
      other_fields:
        - link
    nexusphp:
      cookie: 'xxxxxx'
```

右下角会弹出如下报错：

```
Error loading config: Did not pass schema validation.
```

检查了 WebUI 的 `Manage` - `Database` 的插件列表，也找不到 nexusphp，似乎 FlexGet 没有加载插件目录 `home/qboxl/.local/flexget3/plugins` 下的  `.py` 文件（其权限确认过是 `644`）。是否是 QuickBox Lite 的 FlexGet 插件目录有所更改，或者是我遗漏了在盒子里启用 FlexGet 第三方插件的关键步骤？
